<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DeviceCredentialBroker.Domain\DeviceCredentialBroker.Domain.csproj" />
    <ProjectReference Include="..\DeviceCredentialBroker.Authentication\DeviceCredentialBroker.Authentication.csproj" />
    <ProjectReference Include="..\DeviceCredentialBroker.Application\DeviceCredentialBroker.Application.csproj" />
  </ItemGroup>

</Project>
